services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - website_files:/var/www/html
    depends_on:
      - wordpress
    environment:
      FPM_HOST: wordpress:9000
      DOMAIN_NAME: sguzman.42.fr
    restart: on-failure
  wordpress:
    image: wordpress:6.8.1-php8.1-fpm-alpine
    expose:
      - 9000
    volumes:
      - website_files:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: on-failure

networks:
  default:
    driver: bridge

volumes:
  db_data:
  website_files:
