services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - website_files:/var/www/html
    depends_on:
      - wordpress
    environment:
      FPM_HOST: wordpress
      DOMAIN_NAME: sguzman.42.fr
    restart: on-failure

  wordpress:
    image: wordpress:6.8.1-php8.1-fpm-alpine
    # build: ./requirements/wordpress
    volumes:
      - website_files:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: sguzman # ${DB_USER}
      WORDPRESS_DB_PASSWORD: password # ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress # ${DB_NAME}
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: wordpress # ${DB_NAME}
      MARIADB_USER: sguzman # ${DB_USER}
      MARIADB_PASSWORD: password # ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: password # ${DB_ROOT_PASSWORD}
    restart: on-failure

networks:
  default:
    driver: bridge

volumes:
  db_data:
  website_files: 
