services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - website_files:/var/www/html
    depends_on:
      - wordpress
    environment:
      FPM_HOST: wordpress:9000
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    expose:
      - 9000
    volumes:
      - website_files:/var/www/html
    depends_on:
      - mariadb
      - redis
    environment:
      WORDPRESS_URL: ${DOMAIN_NAME}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${USER}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
      WORDPRESS_DB_NAME: ${DATABASE}
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DATABASE}
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${PASSWORD}
      MARIADB_ROOT_PASSWORD: ${PASSWORD}
    restart: on-failure

  redis:
    build: ./requirements/redis
    expose:
      - 6379
    restart: on-failure

  ftp:
    build: ./requirements/ftp
    ports:
      - 21:21
      - 5000-5100:5000-5100
    volumes:
      - website_files:${HOME}
    environment:
      FTP_PASS: ${PASSWORD} 
    restart: on-failure

  adminer:
    build: ./requirements/adminer
    volumes:
      - website_files:/var/www/html
    restart: on-failure

  static:
    build: ./requirements/static
    volumes:
      - website_files:/var/www/html
    environment:
      TITLE: ${USER}
    restart: on-failure

  cadvisor:
    build: ./requirements/cadvisor
    ports:
      - 8080:8080
    volumes:
      # - /:/rootfs:ro
      - /var/run:/var/run:ro 
      # - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: on-failure

networks:
  default:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sguzman/data/db_data
      o: bind
  website_files:
    driver: local
    driver_opts:
      type: none
      device: /home/sguzman/data/website_files
      o: bind
