services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sguzman
      MYSQL_PASSWORD: password
    restart: on-failure

networks:
  default:
    driver: bridge
