services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    restart: on-failure

networks:
  default:
    driver: bridge
